### ISSUE TITLE
Test Project file missing 

### ISSUE THREAD

**Issue by happydpc** [Karmiska/Darkness#1]
I am very interested in this project with gpu driven implementation. Could you upload some test project file? Thank you.

**Comment by Karmiska** [comment]
Didn't notice this at all. I was like "wait.. I've logged an issue?".

But umh. Right now it's a bit tricky to use the editor side as the rewrite of it is still ongoing. Ie. haven't touched the old one in ages and the new version doesn't actually do much yet.
Also there's quite a bit of hardcoding in the project files and even source code. So it's a bit of a struggle to use.
Mostly because I'm rewriting large parts.

I'd say in general the value of this repo isn't in runnable stuff atm. but rather just code. And even in that case, I would strongly advice against copy pasting stuff as there are tests that don't look like tests. Ie. code that looks like it's doing something relevant, but isn't necessarily doing anything or worse, might actually just break things.

Here's the test project. Just a simple sphere and some textures.
https://drive.google.com/file/d/1icYotDik55JqFkNQcmLNyT4f9zXrzxfj/view?usp=sharing
